version: '3.8'

services:
  meu-postgres:
    image: postgres:16.3
    restart: always
    environment:
      POSTGRES_DB: meu_database
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: meu_password
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local